-- 1. Users Table
CREATE TABLE users (
    id TEXT PRIMARY KEY,
    name TEXT,
    phone TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    walletBalance DECIMAL(10,2) DEFAULT 500.00 CHECK (walletBalance >= 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Providers Table
CREATE TABLE providers (
    id TEXT PRIMARY KEY,
    name TEXT,
    phone TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    verified BOOLEAN DEFAULT false,
    demographic TEXT,
    rating TEXT,
    reviews TEXT,
    tagline TEXT,
    exp TEXT,
    langs TEXT,
    status TEXT DEFAULT 'offline',
    waitTime TEXT,
    imagePath TEXT,
    priceChat INTEGER DEFAULT 10,
    priceCall INTEGER DEFAULT 20,
    priceVideo INTEGER DEFAULT 30,
    walletBalance DECIMAL(10,2) DEFAULT 0.0 CHECK (walletBalance >= 0),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Sessions Table
CREATE TABLE sessions (
    id TEXT PRIMARY KEY,
    userId TEXT REFERENCES users(id) ON DELETE CASCADE,
    providerId TEXT REFERENCES providers(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    rate INTEGER NOT NULL,
    status TEXT DEFAULT 'active',
    startTime TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    duration INTEGER DEFAULT 0,
    cost DECIMAL(10,2) DEFAULT 0.0,
    adminEarnings DECIMAL(10,2) DEFAULT 0.0
);

-- 4. Messages Table
CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId TEXT REFERENCES users(id) ON DELETE CASCADE,
    providerId TEXT REFERENCES providers(id) ON DELETE CASCADE,
    senderId TEXT NOT NULL,
    text TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Inbox Table
CREATE TABLE inbox (
    id TEXT PRIMARY KEY,
    userId TEXT REFERENCES users(id) ON DELETE CASCADE,
    providerId TEXT REFERENCES providers(id) ON DELETE CASCADE,
    date TEXT,
    type TEXT,
    status TEXT,
    message TEXT,
    icon TEXT,
    iconColor TEXT,
    isSystem BOOLEAN DEFAULT false,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Financial Ledger (New - Replaces manual balance updates)
CREATE TABLE wallet_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId TEXT REFERENCES users(id) ON DELETE SET NULL,
    providerId TEXT REFERENCES providers(id) ON DELETE SET NULL,
    sessionId TEXT REFERENCES sessions(id) ON DELETE SET NULL,
    amount DECIMAL(10,2) NOT NULL,
    type TEXT NOT NULL, -- e.g., 'call_deduction', 'provider_earning', 'admin_earning', 'deposit'
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Withdrawals
CREATE TABLE admin_withdrawals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount DECIMAL(10,2) NOT NULL CHECK (amount > 0),
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE provider_withdrawals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    providerId TEXT REFERENCES providers(id) ON DELETE CASCADE,
    amount DECIMAL(10,2) NOT NULL CHECK (amount > 0),
    date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. Functions for secure financial transactions
-- This safely deducts user balance, adds to provider, adds to admin, and records the ledger
CREATE OR REPLACE FUNCTION process_billing_minute(
    p_session_id TEXT,
    p_user_id TEXT,
    p_provider_id TEXT,
    p_rate DECIMAL
) RETURNS BOOLEAN AS $$
DECLARE
    provider_share DECIMAL;
    admin_share DECIMAL;
    current_balance DECIMAL;
BEGIN
    -- Calculate shares
    provider_share := p_rate / 2.0;
    admin_share := p_rate - provider_share;

    -- Check user balance
    SELECT walletBalance INTO current_balance FROM users WHERE id = p_user_id FOR UPDATE;
    
    IF current_balance < p_rate THEN
        RETURN FALSE; -- Insufficient funds
    END IF;

    -- 1. Deduct from User
    UPDATE users SET walletBalance = walletBalance - p_rate WHERE id = p_user_id;
    INSERT INTO wallet_transactions (userId, amount, type, sessionId) VALUES (p_user_id, -p_rate, 'call_deduction', p_session_id);

    -- 2. Add to Provider
    UPDATE providers SET walletBalance = walletBalance + provider_share WHERE id = p_provider_id;
    INSERT INTO wallet_transactions (providerId, amount, type, sessionId) VALUES (p_provider_id, provider_share, 'provider_earning', p_session_id);

    -- 3. Record Admin Earning
    INSERT INTO wallet_transactions (amount, type, sessionId) VALUES (admin_share, 'admin_earning', p_session_id);

    -- 4. Update Session Stats
    UPDATE sessions 
    SET duration = duration + 1, 
        cost = cost + p_rate, 
        adminEarnings = adminEarnings + admin_share 
    WHERE id = p_session_id;

    RETURN TRUE;
END;
$$ LANGUAGE plpgsql;
